# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14efdd8866c90d44efe9a728c4887d6465c2b0ab1b1fc0f93b2b68bdee9538178092a48e77663829bafe78e593c9f8dfe90a1b8df4b85798e3d7340bcb3e5483

test:
  secret_key_base: 1491b8d8ad53e7ad672534f4dbb00f7d48c09d2632529fcdb3d8f7789ebf0a6ce9ed45e31244a6e5b25166e8d2475c1b65f9a5924919a620ac56ba7c12c261c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
